# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-16 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='BarcodeCounter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('counter', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ConcentrationMethod',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Concentration Methods',
                'verbose_name': 'Concentration Method',
            },
        ),
        migrations.CreateModel(
            name='IndexI5',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.CharField(max_length=50, unique=True, verbose_name='Index ID')),
                ('index', models.CharField(max_length=8, verbose_name='Index')),
            ],
            options={
                'verbose_name_plural': 'Indices I5',
                'verbose_name': 'Index I5',
            },
        ),
        migrations.CreateModel(
            name='IndexI7',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_id', models.CharField(max_length=50, unique=True, verbose_name='Index ID')),
                ('index', models.CharField(max_length=8, verbose_name='Index')),
            ],
            options={
                'verbose_name_plural': 'Indices I7',
                'verbose_name': 'Index I7',
            },
        ),
        migrations.CreateModel(
            name='IndexType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Name')),
                ('is_index_i7', models.BooleanField(default=False, verbose_name='Is Index I7?')),
                ('is_index_i5', models.BooleanField(default=False, verbose_name='Is Index I5?')),
            ],
            options={
                'verbose_name_plural': 'Index Types',
                'verbose_name': 'Index Type',
            },
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='ReadLength',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Read Lengths',
                'verbose_name': 'Read Length',
            },
        ),
        migrations.AddField(
            model_name='indexi7',
            name='index_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.IndexType', verbose_name='Index Type'),
        ),
        migrations.AddField(
            model_name='indexi5',
            name='index_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.IndexType', verbose_name='Index Type'),
        ),
    ]
