# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 12:15
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'organisms', app_label='library_sample_shared')
    call_command('loaddata', 'concentration_methods', app_label='library_sample_shared')
    call_command('loaddata', 'read_lengths', app_label='library_sample_shared')
    call_command('loaddata', 'indices', app_label='library_sample_shared')
    call_command('loaddata', 'library_protocols', app_label='library_sample_shared')
    call_command('loaddata', 'library_types', app_label='library_sample_shared')


def unload_fixtures(apps, schema_editor):
    Organism = apps.get_model('library_sample_shared', 'Organism')
    ConcentrationMethod = apps.get_model('library_sample_shared', 'ConcentrationMethod')
    ReadLength = apps.get_model('library_sample_shared', 'ReadLength')
    IndexI7 = apps.get_model('library_sample_shared', 'IndexI7')
    IndexI5 = apps.get_model('library_sample_shared', 'IndexI5')
    IndexType = apps.get_model('library_sample_shared', 'IndexType')
    LibraryProtocol = apps.get_model('library_sample_shared', 'LibraryProtocol')
    LibraryType = apps.get_model('library_sample_shared', 'LibraryType')

    LibraryType.objects.all().delete()
    LibraryProtocol.objects.all().delete()
    IndexType.objects.all().delete()
    IndexI5.objects.all().delete()
    IndexI7.objects.all().delete()
    ReadLength.objects.all().delete()
    ConcentrationMethod.objects.all().delete()
    Organism.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_code=unload_fixtures)
    ]
