# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 12:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='libraryprotocol',
            options={'ordering': ['name'], 'verbose_name': 'Library Protocol', 'verbose_name_plural': 'Library Protocols'},
        ),
    ]
