# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-07 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryprotocol',
            name='status',
            field=models.PositiveIntegerField(default=1, verbose_name='Status'),
        ),
    ]
