# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='organism',
            name='scientific_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Scientific Name'),
        ),
        migrations.AddField(
            model_name='organism',
            name='taxon_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Taxon Identifier'),
        ),
    ]
