# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 11:31
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0002_auto_20180116_1628'),
    ]

    operations = [
        migrations.AddField(
            model_name='indexpair',
            name='char_coord',
            field=models.CharField(default='', max_length=1, verbose_name='Character Coordinate'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='indexpair',
            name='num_coord',
            field=models.PositiveSmallIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Numeric Coordinate'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='indexpair',
            name='coordinate',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
