# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-31 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0002_libraryprotocol_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='libraryprotocol',
            name='obsolete',
            field=models.PositiveIntegerField(default=1, verbose_name='Obsolete'),
        ),
    ]
