# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-22 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0003_libraryprotocol_obsolete'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextype',
            name='obsolete',
            field=models.PositiveIntegerField(default=1, verbose_name='Obsolete'),
        ),
    ]
