# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-22 11:38
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0003_auto_20180122_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexpair',
            name='coordinate',
        ),
    ]
