# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-12-05 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0004_indextype_obsolete'),
    ]

    operations = [
        migrations.AddField(
            model_name='readlength',
            name='obsolete',
            field=models.PositiveIntegerField(default=1, verbose_name='Obsolete'),
        ),
    ]
