# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 21:55
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'indices', app_label='library_sample_shared')


def unload_fixtures(apps, schema_editor):
    IndexI7 = apps.get_model('library_sample_shared', 'IndexI7')
    IndexI7.objects.all().delete()

    IndexI5 = apps.get_model('library_sample_shared', 'IndexI5')
    IndexI5.objects.all().delete()

    IndexType = apps.get_model('library_sample_shared', 'IndexType')
    IndexType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0004_load_read_lengths'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_code=unload_fixtures)
    ]
