# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-24 14:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0005_auto_20180122_1315'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='indexi5',
            name='index_id',
        ),
        migrations.RemoveField(
            model_name='indexi7',
            name='index_id',
        ),
    ]
