# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-01-09 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0005_readlength_obsolete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodecounter',
            name='year',
            field=models.PositiveSmallIntegerField(default=2019, unique=True),
        ),
    ]
