# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 22:15
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'library_protocols', app_label='library_sample_shared')


def unload_fixtures(apps, schema_editor):
    LibraryProtocol = apps.get_model('library_sample_shared', 'LibraryProtocol')
    LibraryProtocol.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0005_load_indices'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_code=unload_fixtures)
    ]
