# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2020-09-28 09:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0006_auto_20190109_1432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodecounter',
            name='year',
            field=models.PositiveSmallIntegerField(default=2020, unique=True),
        ),
    ]
