# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-11 10:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0007_auto_20200207_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextype',
            name='read_type',
            field=models.CharField(choices=[('short', 'short read'), ('long', 'long read')], default='short', max_length=11, verbose_name='Read Type'),
        ),
        migrations.AlterField(
            model_name='indexi5',
            name='index',
            field=models.CharField(max_length=24, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='indexi7',
            name='index',
            field=models.CharField(max_length=24, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='indextype',
            name='index_length',
            field=models.CharField(choices=[('6', '6'), ('8', '8'), ('10', '10'), ('12', '12'), ('24', '24')], default='8', max_length=2, verbose_name='Index Length'),
        ),
    ]
