# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0007_auto_20200207_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indextype',
            name='index_length',
            field=models.CharField(choices=[('6', '6'), ('8', '8'), ('24', '24')], default='8', max_length=2, verbose_name='Index Length'),
        ),
    ]
