# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-20 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0008_auto_20200220_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='indextype',
            name='read_type',
            field=models.CharField(choices=[('short', 'short read'), ('long', 'long read')], default='short', max_length=11, verbose_name='Read Type'),
        ),
        migrations.AlterField(
            model_name='indexi5',
            name='index',
            field=models.CharField(max_length=24, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='indexi7',
            name='index',
            field=models.CharField(max_length=24, verbose_name='Index'),
        ),
    ]
