# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2021-01-26 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0008_auto_20200311_1153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barcodecounter',
            name='year',
            field=models.PositiveSmallIntegerField(default=2021, unique=True),
        ),
    ]
