# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-03-10 10:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0014_auto_20200310_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='indexi5',
            name='index',
            field=models.CharField(max_length=4, verbose_name='Index'),
        ),
        migrations.AlterField(
            model_name='indexi7',
            name='index',
            field=models.CharField(max_length=4, verbose_name='Index'),
        ),
    ]
