# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-14 12:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library_sample_shared', '0002_load_shared_data'),
        ('index_generator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flowcell',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flowcell_id', models.CharField(max_length=50, verbose_name='Flowcell ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lane',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, verbose_name='Name')),
                ('loading_concentration', models.FloatField(verbose_name='Loading Concentration')),
                ('pool', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_generator.Pool', verbose_name='Pool')),
            ],
        ),
        migrations.CreateModel(
            name='Sequencer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('lanes', models.PositiveSmallIntegerField(verbose_name='Number of Lanes')),
                ('lane_capacity', models.PositiveSmallIntegerField(verbose_name='Lane Capacity')),
            ],
        ),
        migrations.AddField(
            model_name='flowcell',
            name='lanes',
            field=models.ManyToManyField(blank=True, related_name='flowcell', to='flowcell.Lane'),
        ),
        migrations.AddField(
            model_name='flowcell',
            name='read_length',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.ReadLength', verbose_name='Read Length'),
        ),
    ]
