# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-21 10:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sequencer',
            name='obsolete',
            field=models.PositiveIntegerField(default=1, verbose_name='Obsolete'),
        ),
    ]
