# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 09:55
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='matrix',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Flowcell Matrix'),
        ),
        migrations.AlterField(
            model_name='flowcell',
            name='flowcell_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Flowcell ID'),
        ),
    ]
