# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 10:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0002_load_sequencers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowcell',
            name='sequencer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowcell.Sequencer', verbose_name='Sequencer'),
        ),
    ]
