# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-04-05 19:52
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0002_auto_20180129_1055'),
    ]

    operations = [
        migrations.AddField(
            model_name='flowcell',
            name='sequences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True, verbose_name='Sequences'),
        ),
    ]
