# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 10:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0003_auto_20170428_1247'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lane',
            name='pool',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_generator.Pool', verbose_name='Pool'),
        ),
    ]
