# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-21 15:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0004_auto_20170428_1252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lane',
            name='loading_concentration',
        ),
        migrations.AddField(
            model_name='flowcell',
            name='loading_concentration',
            field=models.FloatField(blank=True, null=True, verbose_name='Loading Concentration'),
        ),
    ]
