# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 11:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowcell', '0006_auto_20170521_2008'),
    ]

    operations = [
        migrations.AddField(
            model_name='lane',
            name='completed',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
    ]
