# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-25 13:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndexType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Index Type')),
            ],
        ),
    ]
