# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-08-16 08:58
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'sample_fields_data', app_label='library')


def unload_fixture(apps, schema_editor):
    NucleicAcidType = apps.get_model('library', 'NucleicAcidType')
    RNAQuality = apps.get_model('library', 'RNAQuality')
    RNAQuality.objects.all().delete()
    NucleicAcidType.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0008_library_sample'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture)
    ]
