# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-22 07:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0010_load_sample_protocols'),
    ]

    operations = [
        migrations.AlterField(
            model_name='library',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Date'),
        ),
    ]
