# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 11:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0014_barcodecounter'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_pooled',
            field=models.BooleanField(default=False, verbose_name='Is pooled?'),
        ),
    ]
