# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-05 15:39
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library_sample_shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NucleicAcidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('type', models.CharField(choices=[('DNA', 'DNA'), ('RNA', 'RNA')], default='DNA', max_length=3, verbose_name='Type')),
            ],
            options={
                'verbose_name': 'Nucleic Acid Type',
                'verbose_name_plural': 'Nucleic Acid Types',
            },
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('status', models.SmallIntegerField(default=0)),
                ('concentration', models.FloatField(verbose_name='Concentration')),
                ('equal_representation_nucleotides', models.BooleanField(default=True, verbose_name='Equal Representation of Nucleotides')),
                ('sequencing_depth', models.PositiveIntegerField(verbose_name='Sequencing Depth')),
                ('comments', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('is_pooled', models.BooleanField(default=False, verbose_name='Pooled')),
                ('barcode', models.CharField(max_length=9, verbose_name='Barcode')),
                ('index_i7', models.CharField(blank=True, max_length=8, null=True, verbose_name='Index I7')),
                ('index_i5', models.CharField(blank=True, max_length=8, null=True, verbose_name='Index I5')),
                ('dilution_factor', models.PositiveIntegerField(blank=True, default=1, verbose_name='Dilution Factor')),
                ('concentration_facility', models.FloatField(blank=True, null=True, verbose_name='Concentration')),
                ('sample_volume_facility', models.PositiveIntegerField(blank=True, null=True, verbose_name='Sample Volume')),
                ('amount_facility', models.FloatField(blank=True, null=True, verbose_name='Amount')),
                ('size_distribution_facility', models.CharField(blank=True, max_length=200, null=True, verbose_name='Size Distribution')),
                ('comments_facility', models.TextField(blank=True, null=True, verbose_name='Comments')),
                ('rna_quality', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)], verbose_name='RNA Quality')),
                ('amplification_cycles', models.PositiveIntegerField(blank=True, null=True, verbose_name='Amplification cycles')),
                ('is_converted', models.BooleanField(default=False, verbose_name='Converted')),
                ('rna_quality_facility', models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)], verbose_name='RNA Quality (facility)')),
                ('concentration_method', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.ConcentrationMethod', verbose_name='Concentration Method')),
                ('concentration_method_facility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='library_sample_shared.ConcentrationMethod', verbose_name='Concentration Method')),
                ('index_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.IndexType', verbose_name='Index Type')),
                ('library_protocol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.LibraryProtocol', verbose_name='Library Protocol')),
                ('library_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.LibraryType', verbose_name='Library Type')),
                ('nucleic_acid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sample.NucleicAcidType', verbose_name='Nucleic Acid Type')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.Organism', verbose_name='Organism')),
                ('read_length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.ReadLength', verbose_name='Read Length')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('index_reads', models.PositiveSmallIntegerField(default=0, verbose_name='Index Reads')),
            ],
            options={
                'verbose_name': 'Sample',
                'verbose_name_plural': 'Samples',
            },
        ),
    ]
