# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-16 11:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sequencing_depth',
            field=models.FloatField(verbose_name='Sequencing Depth'),
        ),
    ]
