# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 14:23
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'sample_protocols', app_label='sample')
    call_command('loaddata', 'nucleic_acid_types', app_label='sample')


def unload_fixtures(apps, schema_editor):
    SampleProtocol = apps.get_model('sample', 'SampleProtocol')
    NucleicAcidType = apps.get_model('sample', 'NucleicAcidType')

    NucleicAcidType.objects.all().delete()
    SampleProtocol.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_code=unload_fixtures)
    ]
