# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-16 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='date_facility',
        ),
        migrations.AlterField(
            model_name='sample',
            name='amount_facility',
            field=models.FloatField(blank=True, null=True, verbose_name='Amount'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='comments_facility',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='concentration_facility',
            field=models.FloatField(blank=True, null=True, verbose_name='Concentration'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='concentration_method_facility',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='library_sample_shared.ConcentrationMethod', verbose_name='Concentration Method'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='dilution_factor',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Dilution Factor'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='sample_volume_facility',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sample Volume'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='size_distribution_facility',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Size Distribution'),
        ),
    ]
