# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 12:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='index_reads',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Index Reads'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='amplification_cycles',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Amplification cycles'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='is_converted',
            field=models.BooleanField(default=False, verbose_name='Converted'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='is_pooled',
            field=models.BooleanField(default=False, verbose_name='Pooled'),
        ),
    ]
