# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 09:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_load_nucleic_acid_types'),
    ]

    operations = [
        migrations.RenameField('Sample', 'date', 'create_time'),
        migrations.AlterField(
            model_name='sample',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AddField(
            model_name='sample',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
