# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-02-27 15:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_nucleicacidtype_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='index_i5',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Index I5'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='index_i7',
            field=models.CharField(blank=True, max_length=24, null=True, verbose_name='Index I7'),
        ),
    ]
