# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-18 07:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='sample_volume_facility',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Sample Volume (facility)'),
        ),
    ]
