# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-19 13:18
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0003_sample_sample_volume_facility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='rna_quality',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)], verbose_name='RNA Quality'),
        ),
        migrations.AlterField(
            model_name='sample',
            name='rna_quality_facility',
            field=models.FloatField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(11.0)], verbose_name='RNA Quality (facility)'),
        ),
    ]
