# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0004_float_rna_quality'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample',
            name='files',
        ),
        migrations.DeleteModel(
            name='FileSample',
        ),
    ]
