# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 08:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0005_auto_20170420_1043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='dilution_factor',
            field=models.PositiveIntegerField(blank=True, default=1, verbose_name='Dilution Factor (facility)'),
        ),
    ]
