# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-09 15:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sample', '0006_auto_20170502_1059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='name',
            field=models.CharField(max_length=200, verbose_name='Name'),
        ),
    ]
