# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 09:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.Organization', verbose_name='Organization'),
        ),
        migrations.AlterField(
            model_name='user',
            name='pi',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.PrincipalInvestigator', verbose_name='Principal Investigator'),
        ),
    ]
