# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-06 18:08
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial_data', app_label='common')


def unload_fixture(apps, schema_editor):
    Organization = apps.get_model('common', 'Organization')
    PrincipalInvestigator = apps.get_model('common', 'PrincipalInvestigator')
    CostUnit = apps.get_model('common', 'CostUnit')
    CostUnit.objects.all().delete()
    PrincipalInvestigator.objects.all().delete()
    Organization.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture)
    ]
