# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 17:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_load_initial_data'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costunit',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='principalinvestigator',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ['last_name', 'first_name']},
        ),
    ]
