# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-19 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_auto_20171117_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='costunit',
            options={'ordering': ['name'], 'verbose_name': 'Cost Unit', 'verbose_name_plural': 'Cost Units'},
        ),
        migrations.AlterModelOptions(
            name='principalinvestigator',
            options={'ordering': ['organization__name', 'name'], 'verbose_name': 'Principal Investigator', 'verbose_name_plural': 'Principal Investigators'},
        ),
        migrations.AlterField(
            model_name='costunit',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='principalinvestigator',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Phone'),
        ),
    ]
