# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-17 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Cost Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Principal Investigator')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('telephone', models.CharField(max_length=100, verbose_name='Telephone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('costunit', models.ManyToManyField(to='researcher.CostUnit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.Organization')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.PrincipalInvestigator')),
            ],
        ),
    ]
