# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-07-01 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CostUnit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Cost Unit')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Organization')),
            ],
        ),
        migrations.CreateModel(
            name='PrincipalInvestigator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Principal Investigator')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.Organization')),
            ],
        ),
        migrations.CreateModel(
            name='Researcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='First name')),
                ('last_name', models.CharField(max_length=150, verbose_name='Last name')),
                ('phone', models.CharField(max_length=100, verbose_name='Phone')),
                ('email', models.CharField(max_length=100, verbose_name='Email')),
                ('cost_unit', models.ManyToManyField(to='researcher.CostUnit', verbose_name='Cost Unit')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.Organization', verbose_name='Organization')),
                ('pi', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.PrincipalInvestigator', verbose_name='Principal Investigator')),
            ],
        ),
        migrations.AddField(
            model_name='costunit',
            name='pi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='researcher.PrincipalInvestigator', verbose_name='Principal Investigator'),
        ),
    ]
