# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-20 11:59
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixture(apps, schema_editor):
    call_command('loaddata', 'initial_data_organizations', app_label='researcher')
    call_command('loaddata', 'initial_data_pis', app_label='researcher')
    call_command('loaddata', 'initial_data_cost_units', app_label='researcher')


def unload_fixture(apps, schema_editor):
    Organization = apps.get_model('researcher', 'Organization')
    PrincipalInvestigator = apps.get_model('researcher', 'PrincipalInvestigator')
    CostUnit = apps.get_model('researcher', 'CostUnit')
    Researcher = apps.get_model('researcher', 'Researcher')
    Organization.objects.all().delete()
    PrincipalInvestigator.objects.all().delete()
    CostUnit.objects.all().delete()
    Researcher.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('researcher', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixture, reverse_code=unload_fixture)
    ]
