# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 10:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0001_initial'),
        ('sample', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('loaded', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Loaded')),
                ('libraries', models.ManyToManyField(blank=True, related_name='pool', to='library.Library')),
                ('samples', models.ManyToManyField(blank=True, related_name='pool', to='sample.Sample')),
            ],
        ),
        migrations.CreateModel(
            name='PoolSize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('multiplier', models.PositiveSmallIntegerField(default=1, verbose_name='Multiplier')),
                ('size', models.PositiveSmallIntegerField(verbose_name='Size')),
            ],
        ),
        migrations.AddField(
            model_name='pool',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index_generator.PoolSize', verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='pool',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
        migrations.AddField(
            model_name='pool',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='pool',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
        migrations.AlterModelOptions(
            name='poolsize',
            options={'ordering': ['multiplier', 'size']},
        ),
    ]
