# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-18 10:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('library', '0002_load_initial_data'),
        ('sample', '0002_load_initial_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Name')),
                ('size', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Pool Size')),
                ('loaded', models.PositiveSmallIntegerField(blank=True, default=0, verbose_name='Loaded')),
                ('file', models.FileField(blank=True, null=True, upload_to='pools/%Y/%m/%d/')),
                ('libraries', models.ManyToManyField(blank=True, related_name='pool', to='library.Library')),
                ('samples', models.ManyToManyField(blank=True, related_name='pool', to='sample.Sample')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
