# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2018-11-05 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='comment',
            field=models.TextField(blank=True, verbose_name='Comment'),
        ),
    ]
