# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 13:38
from __future__ import unicode_literals

from django.db import migrations
from django.core.management import call_command


def load_fixtures(apps, schema_editor):
    call_command('loaddata', 'pool_sizes', app_label='index_generator')


def unload_fixtures(apps, schema_editor):
    PoolSize = apps.get_model('index_generator', 'PoolSize')
    PoolSize.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(load_fixtures, reverse_code=unload_fixtures)
    ]
