# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 08:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0002_auto_20170418_1310'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='size',
        ),
    ]
