# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-22 11:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index_generator', '0005_pool_size'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pool',
            name='file',
        ),
    ]
