# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 12:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0017_sample_is_pooled'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pool',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('libraries', models.ManyToManyField(blank=True, to='library.Library')),
            ],
        ),
    ]
