# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-28 20:17
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pooling', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pooling',
            name='buffer_volume',
        ),
        migrations.RemoveField(
            model_name='pooling',
            name='concentration_c2',
        ),
        migrations.RemoveField(
            model_name='pooling',
            name='percentage_library',
        ),
        migrations.RemoveField(
            model_name='pooling',
            name='sample_volume',
        ),
        migrations.RemoveField(
            model_name='pooling',
            name='volume_to_pool',
        ),
    ]
