# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-11-21 10:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooling', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pooling',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
    ]
