# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-05 13:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pooling', '0005_poolfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='pool',
            name='size',
            field=models.IntegerField(blank=True, default=0, verbose_name='Pool Size'),
        ),
    ]
