# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-14 13:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ('flowcell', '0002_flowcell_requests'),
        ('library_sample_shared', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FixedCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('sequencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='flowcell.Sequencer')),
            ],
            options={
                'verbose_name': 'Fixed Cost',
                'verbose_name_plural': 'Fixed Costs',
            },
        ),
        migrations.CreateModel(
            name='LibraryPreparationCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('library_protocol', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.LibraryProtocol')),
            ],
            options={
                'verbose_name': 'Library Preparation Cost',
                'verbose_name_plural': 'Library Preparation Costs',
            },
        ),
        migrations.CreateModel(
            name='SequencingCosts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('read_length', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='library_sample_shared.ReadLength', verbose_name='Read Length')),
                ('sequencer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flowcell.Sequencer')),
            ],
            options={
                'verbose_name': 'Sequencing Cost',
                'verbose_name_plural': 'Sequencing Costs',
            },
        ),
        migrations.AlterUniqueTogether(
            name='sequencingcosts',
            unique_together=set([('sequencer', 'read_length')]),
        ),
    ]
