# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import month.models


class Migration(migrations.Migration):

    dependencies = [
        ('invoicing', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoicingReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='Create Time')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('month', month.models.MonthField(unique=True, verbose_name='Month')),
                ('report', models.FileField(upload_to='invoicing/%Y/%m/', verbose_name='Report')),
            ],
            options={
                'verbose_name': 'Invoicing Report',
                'verbose_name_plural': 'Invoicing Report',
                'ordering': ['-month'],
            },
        ),
    ]
