# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-09 14:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sample', '0002_load_initial_data'),
        ('library', '0002_load_initial_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.SmallIntegerField(default=0)),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField(null=True)),
                ('deep_seq_request', models.FileField(blank=True, null=True, upload_to='requests/%Y/%m/%d/')),
                ('libraries', models.ManyToManyField(blank=True, to='library.Library')),
                ('samples', models.ManyToManyField(blank=True, to='sample.Sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
