# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-29 08:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('library', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sample', '0002_load_nucleic_acid_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('file', models.FileField(upload_to='request_files/%Y/%m/%d/')),
            ],
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='Name')),
                ('date_created', models.DateTimeField(auto_now_add=True, verbose_name='Date')),
                ('description', models.TextField()),
                ('deep_seq_request', models.FileField(blank=True, null=True, upload_to='deep_sequencing_requests/%Y/%m/%d/', verbose_name='Deep Sequencing Request')),
                ('files', models.ManyToManyField(blank=True, related_name='request', to='request.FileRequest')),
                ('libraries', models.ManyToManyField(blank=True, related_name='request', to='library.Library')),
                ('samples', models.ManyToManyField(blank=True, related_name='request', to='sample.Sample')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
