# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-18 14:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='project_type',
            field=models.CharField(max_length=100, null=True, verbose_name='Project Type'),
        ),
        migrations.AlterField(
            model_name='request',
            name='researcher_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='researcher.Researcher'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='request',
            name='terms_of_use_accept',
            field=models.BooleanField(default=True),
        ),
    ]
