# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 08:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('file', models.FileField(upload_to='request_files/%Y/%m/%d/')),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='deep_seq_request',
            field=models.FileField(blank=True, null=True, upload_to='deep_sequencing_requests/%Y/%m/%d/', verbose_name='Deep Sequencing Request'),
        ),
        migrations.AddField(
            model_name='request',
            name='files',
            field=models.ManyToManyField(blank=True, related_name='request', to='request.FileRequest'),
        ),
    ]
