# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 08:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import request.models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='cost_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='common.CostUnit', verbose_name='Cost Unit'),
        ),
        migrations.AlterField(
            model_name='request',
            name='user',
            field=models.ForeignKey(on_delete=models.SET(request.models.get_sentinel_user), to=settings.AUTH_USER_MODEL, verbose_name='User'),
        ),
    ]
