# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 09:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.RenameField('Request', 'date_created', 'create_time'),
        migrations.AlterField(
            model_name='request',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Create Time'),
        ),
        migrations.AddField(
            model_name='request',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
