# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-12-12 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='sequenced',
            field=models.BooleanField(default=False, verbose_name='Sequenced'),
        ),
    ]
