# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-08 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FilePIApproval',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('file', models.FileField(upload_to='approvals/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='request',
            name='pi_approval',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='request.FilePIApproval', verbose_name="PI's Approval"),
        ),
    ]
