# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-12 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0002_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='samples_submitted',
            field=models.BooleanField(default=False, verbose_name='Samples Submitted'),
        ),
    ]
