# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 19:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0014_auto_20160831_1152'),
        ('request', '0002_auto_20160718_1647'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='libraries',
            field=models.ManyToManyField(to='library.Library'),
        ),
    ]
