# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0014_auto_20160831_1152'),
        ('request', '0003_request_libraries'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='samples',
            field=models.ManyToManyField(to='library.Sample'),
        ),
    ]
