# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-31 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('request', '0004_request_samples'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='libraries',
            field=models.ManyToManyField(blank=True, to='library.Library'),
        ),
        migrations.AlterField(
            model_name='request',
            name='samples',
            field=models.ManyToManyField(blank=True, to='library.Sample'),
        ),
    ]
