# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-19 10:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('library_preparation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarypreparation',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Create Time'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='librarypreparation',
            name='update_time',
            field=models.DateTimeField(auto_now=True, verbose_name='Update Time'),
        ),
    ]
