# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 09:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_preparation', '0002_add_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='librarypreparation',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
    ]
