# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-21 11:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('library_preparation', '0002_add_timestamps'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='librarypreparation',
            name='starting_volume',
        ),
        migrations.AddField(
            model_name='librarypreparation',
            name='comments',
            field=models.TextField(blank=True, null=True, verbose_name='Comments'),
        ),
        migrations.AddField(
            model_name='librarypreparation',
            name='qpcr_result',
            field=models.FloatField(blank=True, null=True, verbose_name='qPCR Result'),
        ),
    ]
